repos:
  # black python autoformatting
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black
        exclude: (dist|json|data|data_format)/
        description: "Black: The uncompromising Python code formatter"
        entry: black
        # args: ['--check']
    # flake8 python linter with all the fixins
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8
        exclude: ((dist|json|data|data_format)/|__init__.py)
        description: "Enforce style consistency"
    # additional configuration of flake8 and extensions in .flake8
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort
        description: "Sort your imports"
        exclude: ((dist|json|data|data_format)/|__init__.py)
        args: ["--profile", "black"]
        # args: ['--check-only']
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        name: interrogate
        exclude: ((dist|json|data|data_format)/|__init__.py)
        description: "Checks code base for missing docstrings"
        args: ["--ignore-init-module", "--ignore-init-method", "-vv"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # list of definitions and supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace # removes any whitespace at the ends of lines
      - id: check-toml # check toml syntax by loading all toml files
      - id: check-yaml # check yaml syntax by loading all yaml files
      - id: check-json # check-json syntax by loading all json files
      - id: check-merge-conflict # check for files with merge conflict strings
        args: ["--assume-in-merge"] #  and run this check even when not explicitly in a merge
      - id: check-added-large-files # check that no "large" files have been added
        args: ["--maxkb=10240"] #  where large means 10MB+, as in Hugging Face's git server
      - id: debug-statements # check for python debug statements (import pdb, breakpoint, etc.)
      - id: detect-private-key # checks for private keys (BEGIN X PRIVATE KEY, etc.)
