repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black
        exclude: (dist|json|data|data_format)/
        description: "Black: The uncompromising Python code formatter"
        entry: black
        # args: ['--check']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8
        exclude: ((dist|json|data|data_format)/|__init__.py)
        description: "Enforce style consistency"
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort
        description: "Sort your imports"
        exclude: ((dist|json|data|data_format)/|__init__.py)
        args: ["--profile", "black"]
        # args: ['--check-only']
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        name: interrogate
        exclude: ((dist|json|data|data_format)/|__init__.py)
        description: "Checks code base for missing docstrings"
        args: ["--ignore-init-module", "--ignore-init-method", "-vv"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
        description: Prevents commit of files > 1 MB
        args: ["--maxkb=1000"]
